# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fourbins.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        Form.setMinimumSize(QtCore.QSize(1280, 800))
        Form.setMaximumSize(QtCore.QSize(1280, 800))

        Form.setStyleSheet("background-color: #F4F7FE;")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1191, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 8, 1, 1)
        self.signalLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.signalLabel_2.setMinimumSize(QtCore.QSize(15, 12))
        self.signalLabel_2.setMaximumSize(QtCore.QSize(15, 12))
        self.signalLabel_2.setText("")
        self.signalLabel_2.setPixmap(QtGui.QPixmap("../icons/wifi_full.png"))
        self.signalLabel_2.setScaledContents(True)
        self.signalLabel_2.setObjectName("signalLabel_2")
        self.gridLayout_2.addWidget(self.signalLabel_2, 0, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.logoLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.logoLabel_2.setMinimumSize(QtCore.QSize(230, 30))
        self.logoLabel_2.setMaximumSize(QtCore.QSize(230, 30))
        self.logoLabel_2.setText("")
        self.logoLabel_2.setPixmap(QtGui.QPixmap(":/icons/icons/Logo.png"))
        self.logoLabel_2.setScaledContents(True)
        self.logoLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel_2.setObjectName("logoLabel_2")
        self.gridLayout_2.addWidget(self.logoLabel_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(24, 12))
        self.label_5.setMaximumSize(QtCore.QSize(24, 12))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../icons/battery_full.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 9, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 6, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        self.wifiLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.wifiLabel_2.setMinimumSize(QtCore.QSize(15, 12))
        self.wifiLabel_2.setMaximumSize(QtCore.QSize(15, 12))
        self.wifiLabel_2.setText("")
        self.wifiLabel_2.setPixmap(QtGui.QPixmap("../icons/Signal_Full.png"))
        self.wifiLabel_2.setScaledContents(True)
        self.wifiLabel_2.setObjectName("wifiLabel_2")
        self.gridLayout_2.addWidget(self.wifiLabel_2, 0, 7, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(60, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 10, 1, 1)
        self.frmBox2 = QtWidgets.QFrame(Form)
        self.frmBox2.setGeometry(QtCore.QRect(70, 150, 520, 240))
        self.frmBox2.setStyleSheet("QFrame {\n"
"    background: #fff;\n"
"    border-radius: 16px;\n"
"    border: none;\n"
"    /* 阴影可选 */\n"
"}\n"
"")
        self.frmBox2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBox2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBox2.setObjectName("frmBox2")
        self.Box2 = QtWidgets.QLabel(self.frmBox2)
        self.Box2.setGeometry(QtCore.QRect(50, 30, 160, 160))
        self.Box2.setText("")
        self.Box2.setPixmap(QtGui.QPixmap(":/icons/icons/Box.png"))
        self.Box2.setScaledContents(True)
        self.Box2.setObjectName("Box2")
        self.Name2 = QtWidgets.QLabel(self.frmBox2)
        self.Name2.setGeometry(QtCore.QRect(250, 40, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Name2.setFont(font)
        self.Name2.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-weight: bold;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Name2.setObjectName("Name2")
        self.Status2 = QtWidgets.QLabel(self.frmBox2)
        self.Status2.setGeometry(QtCore.QRect(270, 75, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Status2.setFont(font)
        self.Status2.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Status2.setObjectName("Status2")
        self.Light2 = QtWidgets.QLabel(self.frmBox2)
        self.Light2.setGeometry(QtCore.QRect(250, 85, 12, 12))
        self.Light2.setStyleSheet("QLabel {\n"
"    background: #23c037;       /* 绿色，可根据需求调整色值 */\n"
"    border-radius: 6px;        /* 半径=宽高一半，变成圆 */\n"
"    min-width: 12px;\n"
"    min-height: 12px;\n"
"    max-width: 12px;\n"
"    max-height: 12px;\n"
"    border: none;\n"
"}\n"
"")
        self.Light2.setText("")
        self.Light2.setObjectName("Light2")
        self.Button2 = QtWidgets.QPushButton(self.frmBox2)
        self.Button2.setGeometry(QtCore.QRect(250, 140, 220, 50))
        self.Button2.setMinimumSize(QtCore.QSize(140, 30))
        self.Button2.setMaximumSize(QtCore.QSize(10000000, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button2.setFont(font)
        self.Button2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    color: #FFF;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 140px;\n"
"    min-height: 30px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.Button2.setObjectName("Button2")
        self.Address2 = QtWidgets.QLabel(self.frmBox2)
        self.Address2.setGeometry(QtCore.QRect(270, 100, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Address2.setFont(font)
        self.Address2.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Address2.setObjectName("Address2")
        self.frmBox1 = QtWidgets.QFrame(Form)
        self.frmBox1.setGeometry(QtCore.QRect(620, 150, 520, 240))
        self.frmBox1.setStyleSheet("QFrame {\n"
"    background: #fff;\n"
"    border-radius: 16px;\n"
"    border: none;\n"
"    /* 阴影可选 */\n"
"}\n"
"")
        self.frmBox1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBox1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBox1.setObjectName("frmBox1")
        self.Box1 = QtWidgets.QLabel(self.frmBox1)
        self.Box1.setGeometry(QtCore.QRect(40, 40, 160, 160))
        self.Box1.setText("")
        self.Box1.setPixmap(QtGui.QPixmap(":/icons/icons/Box.png"))
        self.Box1.setScaledContents(True)
        self.Box1.setObjectName("Box1")
        self.Name1 = QtWidgets.QLabel(self.frmBox1)
        self.Name1.setGeometry(QtCore.QRect(250, 40, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Name1.setFont(font)
        self.Name1.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-weight: bold;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Name1.setObjectName("Name1")
        self.Status1 = QtWidgets.QLabel(self.frmBox1)
        self.Status1.setGeometry(QtCore.QRect(270, 75, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Status1.setFont(font)
        self.Status1.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Status1.setObjectName("Status1")
        self.Light1 = QtWidgets.QLabel(self.frmBox1)
        self.Light1.setGeometry(QtCore.QRect(250, 85, 12, 12))
        self.Light1.setStyleSheet("QLabel {\n"
"    background: #23c037;       /* 绿色，可根据需求调整色值 */\n"
"    border-radius: 6px;        /* 半径=宽高一半，变成圆 */\n"
"    min-width: 12px;\n"
"    min-height: 12px;\n"
"    max-width: 12px;\n"
"    max-height: 12px;\n"
"    border: none;\n"
"}\n"
"")
        self.Light1.setText("")
        self.Light1.setObjectName("Light1")
        self.Button1 = QtWidgets.QPushButton(self.frmBox1)
        self.Button1.setGeometry(QtCore.QRect(250, 140, 220, 50))
        self.Button1.setMinimumSize(QtCore.QSize(140, 30))
        self.Button1.setMaximumSize(QtCore.QSize(1000, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button1.setFont(font)
        self.Button1.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    color: #FFF;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 140px;\n"
"    min-height: 30px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.Button1.setObjectName("Button1")
        self.Address1 = QtWidgets.QLabel(self.frmBox1)
        self.Address1.setGeometry(QtCore.QRect(270, 100, 190, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Address1.setFont(font)
        self.Address1.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Address1.setObjectName("Address1")
        self.frmBox3 = QtWidgets.QFrame(Form)
        self.frmBox3.setGeometry(QtCore.QRect(70, 420, 520, 240))
        self.frmBox3.setStyleSheet("QFrame {\n"
"    background: #fff;\n"
"    border-radius: 16px;\n"
"    border: none;\n"
"    /* 阴影可选 */\n"
"}\n"
"")
        self.frmBox3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBox3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBox3.setObjectName("frmBox3")
        self.Box3 = QtWidgets.QLabel(self.frmBox3)
        self.Box3.setGeometry(QtCore.QRect(50, 30, 160, 160))
        self.Box3.setText("")
        self.Box3.setPixmap(QtGui.QPixmap(":/icons/icons/Box.png"))
        self.Box3.setScaledContents(True)
        self.Box3.setObjectName("Box3")
        self.Name3 = QtWidgets.QLabel(self.frmBox3)
        self.Name3.setGeometry(QtCore.QRect(250, 40, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Name3.setFont(font)
        self.Name3.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-weight: bold;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Name3.setObjectName("Name3")
        self.Status3 = QtWidgets.QLabel(self.frmBox3)
        self.Status3.setGeometry(QtCore.QRect(270, 75, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Status3.setFont(font)
        self.Status3.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Status3.setObjectName("Status3")
        self.Light3 = QtWidgets.QLabel(self.frmBox3)
        self.Light3.setGeometry(QtCore.QRect(250, 85, 12, 12))
        self.Light3.setStyleSheet("QLabel {\n"
"    background: #23c037;       /* 绿色，可根据需求调整色值 */\n"
"    border-radius: 6px;        /* 半径=宽高一半，变成圆 */\n"
"    min-width: 12px;\n"
"    min-height: 12px;\n"
"    max-width: 12px;\n"
"    max-height: 12px;\n"
"    border: none;\n"
"}\n"
"")
        self.Light3.setText("")
        self.Light3.setObjectName("Light3")
        self.Button3 = QtWidgets.QPushButton(self.frmBox3)
        self.Button3.setGeometry(QtCore.QRect(250, 140, 220, 50))
        self.Button3.setMinimumSize(QtCore.QSize(140, 30))
        self.Button3.setMaximumSize(QtCore.QSize(1000, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button3.setFont(font)
        self.Button3.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    color: #FFF;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 140px;\n"
"    min-height: 30px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.Button3.setObjectName("Button3")
        self.Address3 = QtWidgets.QLabel(self.frmBox3)
        self.Address3.setGeometry(QtCore.QRect(270, 100, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Address3.setFont(font)
        self.Address3.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37)\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Address3.setObjectName("Address3")
        self.frmBox4 = QtWidgets.QFrame(Form)
        self.frmBox4.setGeometry(QtCore.QRect(620, 420, 520, 240))
        self.frmBox4.setStyleSheet("QFrame {\n"
"    background: #fff;\n"
"    border-radius: 16px;\n"
"    border: none;\n"
"    /* 阴影可选 */\n"
"}\n"
"")
        self.frmBox4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frmBox4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frmBox4.setObjectName("frmBox4")
        self.Box4 = QtWidgets.QLabel(self.frmBox4)
        self.Box4.setGeometry(QtCore.QRect(50, 30, 160, 160))
        self.Box4.setText("")
        self.Box4.setPixmap(QtGui.QPixmap(":/icons/icons/Box.png"))
        self.Box4.setScaledContents(True)
        self.Box4.setObjectName("Box4")
        self.Name4 = QtWidgets.QLabel(self.frmBox4)
        self.Name4.setGeometry(QtCore.QRect(250, 40, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Name4.setFont(font)
        self.Name4.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-weight: bold;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Name4.setObjectName("Name4")
        self.Status4 = QtWidgets.QLabel(self.frmBox4)
        self.Status4.setGeometry(QtCore.QRect(270, 75, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Status4.setFont(font)
        self.Status4.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Status4.setObjectName("Status4")
        self.light4 = QtWidgets.QLabel(self.frmBox4)
        self.light4.setGeometry(QtCore.QRect(250, 85, 12, 12))
        self.light4.setStyleSheet("QLabel {\n"
"    background: #23c037;       /* 绿色，可根据需求调整色值 */\n"
"    border-radius: 6px;        /* 半径=宽高一半，变成圆 */\n"
"    min-width: 12px;\n"
"    min-height: 12px;\n"
"    max-width: 12px;\n"
"    max-height: 12px;\n"
"    border: none;\n"
"}\n"
"")
        self.light4.setText("")
        self.light4.setObjectName("light4")
        self.Button4 = QtWidgets.QPushButton(self.frmBox4)
        self.Button4.setGeometry(QtCore.QRect(250, 140, 220, 50))
        self.Button4.setMinimumSize(QtCore.QSize(140, 30))
        self.Button4.setMaximumSize(QtCore.QSize(10000, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Button4.setFont(font)
        self.Button4.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    color: #FFF;\n"
"    border-radius: 8px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 140px;\n"
"    min-height: 30px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.Button4.setObjectName("Button4")
        self.Address4 = QtWidgets.QLabel(self.frmBox4)
        self.Address4.setGeometry(QtCore.QRect(270, 100, 190, 30))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        self.Address4.setFont(font)
        self.Address4.setStyleSheet("QLabel {\n"
"    color:  rgb(37, 37, 37);\n"
"    font-family: \'Microsoft YaHei\';\n"
"    background: transparent;\n"
"}\n"
"")
        self.Address4.setObjectName("Address4")
        self.ConfirmButton = QtWidgets.QPushButton(Form)
        self.ConfirmButton.setGeometry(QtCore.QRect(70, 700, 520, 54))
        self.ConfirmButton.setMinimumSize(QtCore.QSize(0, 54))
        self.ConfirmButton.setMaximumSize(QtCore.QSize(10000, 54))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.ConfirmButton.setFont(font)
        self.ConfirmButton.setMouseTracking(False)
        self.ConfirmButton.setTabletTracking(False)
        self.ConfirmButton.setAcceptDrops(False)
        self.ConfirmButton.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    color: #FFF;\n"
"    border-radius: 16px;\n"
"    font-size: 18px;\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: bold;\n"
"    min-width: 514px;\n"
"    min-height: 54px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background: #f0f6ff;\n"
"}\n"
"")
        self.ConfirmButton.setAutoDefault(False)
        self.ConfirmButton.setDefault(False)
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.BackhomepageButton = QtWidgets.QPushButton(Form)
        self.BackhomepageButton.setGeometry(QtCore.QRect(1040, 720, 111, 27))
        self.BackhomepageButton.setMinimumSize(QtCore.QSize(111, 0))
        self.BackhomepageButton.setMaximumSize(QtCore.QSize(111, 16777215))
        self.BackhomepageButton.setStyleSheet("QPushButton {\n"
"    background: transparent;    /* 没有背景 */\n"
"    border: none;               /* 没有边框 */\n"
"    color: rgba(37, 37, 37, 80);  /* 浅灰色，和界面一致 */\n"
"    font-size: 20px;            /* 字体大小，可按实际需求调 */\n"
"    font-family: \'Microsoft YaHei\';\n"
"    font-weight: normal;        /* 不加粗 */\n"
"    padding: 0 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"    color: #888e99;             /* 按下时颜色略深 */\n"
"}\n"
"")
        self.BackhomepageButton.setObjectName("BackhomepageButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "17:04"))
        self.Name2.setText(_translate("Form", "2号货仓"))
        self.Status2.setText(_translate("Form", "空闲状态"))
        self.Button2.setText(_translate("Form", "打开仓门"))
        self.Address2.setText(_translate("Form", "地址："))
        self.Name1.setText(_translate("Form", "1号货仓"))
        self.Status1.setText(_translate("Form", "空闲状态"))
        self.Button1.setText(_translate("Form", "打开仓门"))
        self.Address1.setText(_translate("Form", "地址："))
        self.Name3.setText(_translate("Form", "3号货仓"))
        self.Status3.setText(_translate("Form", "空闲状态"))
        self.Button3.setText(_translate("Form", "打开仓门"))
        self.Address3.setText(_translate("Form", "地址："))
        self.Name4.setText(_translate("Form", "4号货仓"))
        self.Status4.setText(_translate("Form", "空闲状态"))
        self.Button4.setText(_translate("Form", "打开仓门"))
        self.Address4.setText(_translate("Form", "地址："))
        self.ConfirmButton.setText(_translate("Form", "确认派送"))
        self.BackhomepageButton.setText(_translate("Form", "<<<返回"))
import ui_pkg.scripts.Four_cabin.resources_rc
