# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 800))
        MainWindow.setStyleSheet("QMainWindow {\n"
"background-color: #F4F7FE"
"    background-repeat: no-repeat;             /* 不重复背景 */\n"
"    background-position: center;             /* 背景居中 */\n"
"    background-size: cover;                  /* 背景自动适应窗口大小 */\n"
"}\n"
"")
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblBattery = QtWidgets.QLabel(self.centralwidget)
        self.lblBattery.setMinimumSize(QtCore.QSize(24, 12))
        self.lblBattery.setMaximumSize(QtCore.QSize(24, 12))
        self.lblBattery.setText("")
        self.lblBattery.setPixmap(QtGui.QPixmap(":/icons/icons/battery_full.png"))
        self.lblBattery.setScaledContents(True)
        self.lblBattery.setObjectName("lblBattery")
        self.gridLayout.addWidget(self.lblBattery, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 70, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.lblSignal = QtWidgets.QLabel(self.centralwidget)
        self.lblSignal.setMinimumSize(QtCore.QSize(15, 12))
        self.lblSignal.setMaximumSize(QtCore.QSize(15, 12))
        self.lblSignal.setText("")
        self.lblSignal.setPixmap(QtGui.QPixmap(":/icons/icons/Signal_Full.png"))
        self.lblSignal.setScaledContents(True)
        self.lblSignal.setObjectName("lblSignal")
        self.gridLayout.addWidget(self.lblSignal, 0, 5, 1, 1)
        self.lblLogo = QtWidgets.QLabel(self.centralwidget)
        self.lblLogo.setMinimumSize(QtCore.QSize(240, 30))
        self.lblLogo.setMaximumSize(QtCore.QSize(240, 30))
        self.lblLogo.setToolTipDuration(0)
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/icons/icons/Logo.png"))
        self.lblLogo.setScaledContents(True)
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.gridLayout.addWidget(self.lblLogo, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(60, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 8, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 6, 1, 1)
        self.lblwifi = QtWidgets.QLabel(self.centralwidget)
        self.lblwifi.setMinimumSize(QtCore.QSize(15, 12))
        self.lblwifi.setMaximumSize(QtCore.QSize(15, 12))
        self.lblwifi.setText("")
        self.lblwifi.setPixmap(QtGui.QPixmap(":/icons/icons/wifi_full.png"))
        self.lblwifi.setScaledContents(True)
        self.lblwifi.setObjectName("lblwifi")
        self.gridLayout.addWidget(self.lblwifi, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTime = QtWidgets.QLabel(self.centralwidget)
        self.lblTime.setMinimumSize(QtCore.QSize(0, 40))
        self.lblTime.setMaximumSize(QtCore.QSize(16777215, 1000))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.lblTime.setFont(font)
        self.lblTime.setScaledContents(True)
        self.lblTime.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTime.setObjectName("lblTime")
        self.verticalLayout.addWidget(self.lblTime)
        self.lblDate = QtWidgets.QLabel(self.centralwidget)
        self.lblDate.setEnabled(True)
        self.lblDate.setMinimumSize(QtCore.QSize(0, 30))
        self.lblDate.setMaximumSize(QtCore.QSize(1888888, 300))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(6)
        self.lblDate.setFont(font)
        self.lblDate.setScaledContents(False)
        self.lblDate.setAlignment(QtCore.Qt.AlignCenter)
        self.lblDate.setObjectName("lblDate")
        self.verticalLayout.addWidget(self.lblDate)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 350))
        self.frame.setMaximumSize(QtCore.QSize(500, 350))
        self.frame.setStyleSheet("QFrame {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #61A9FF, stop:1 #182490);\n"
"    border-radius: 15px;\n"
"    padding: 20px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblCreateTaskTitle = QtWidgets.QLabel(self.frame)
        self.lblCreateTaskTitle.setGeometry(QtCore.QRect(150, 180, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lblCreateTaskTitle.setFont(font)
        self.lblCreateTaskTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblCreateTaskTitle.setAutoFillBackground(False)
        self.lblCreateTaskTitle.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"    font-family: \"Microsoft JhengHei\"; /* 设置字体 */\n"
"    font-weight: bold; /* 设置加粗 */\n"
"    color: white; /* 设置文字颜色 */\n"
"    padding-top: 10px; /* 上部间距 */\n"
"    text-align: center; /* 居中对齐 */\n"
"}\n"
"")
        self.lblCreateTaskTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCreateTaskTitle.setObjectName("lblCreateTaskTitle")
        self.lblCreateTaskIcon = QtWidgets.QLabel(self.frame)
        self.lblCreateTaskIcon.setEnabled(True)
        self.lblCreateTaskIcon.setGeometry(QtCore.QRect(150, 40, 180, 161))
        self.lblCreateTaskIcon.setMinimumSize(QtCore.QSize(149, 123))
        self.lblCreateTaskIcon.setMaximumSize(QtCore.QSize(180, 180))
        self.lblCreateTaskIcon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblCreateTaskIcon.setStyleSheet("QLabel {\n"
"    background: transparent;\n"
"}\n"
"")
        self.lblCreateTaskIcon.setText("")
        self.lblCreateTaskIcon.setPixmap(QtGui.QPixmap(":/icons/icons/package.png"))
        self.lblCreateTaskIcon.setScaledContents(True)
        self.lblCreateTaskIcon.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCreateTaskIcon.setWordWrap(False)
        self.lblCreateTaskIcon.setObjectName("lblCreateTaskIcon")
        self.lblCreateTaskSubtitle = QtWidgets.QLabel(self.frame)
        self.lblCreateTaskSubtitle.setGeometry(QtCore.QRect(140, 240, 211, 52))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lblCreateTaskSubtitle.setFont(font)
        self.lblCreateTaskSubtitle.setAutoFillBackground(False)
        self.lblCreateTaskSubtitle.setStyleSheet("QLabel{\n"
"    background: transparent;\n"
"    font-family: \"Microsoft JhengHei\"; /* 设置字体 */\n"
"    font-weight: normal; /* 设置普通字体 */\n"
"    color: white; /* 设置文字颜色 */\n"
"    padding-top: 5px; /* 上部间距 */\n"
"    text-align: center; /* 居中对齐 */\n"
"}")
        self.lblCreateTaskSubtitle.setScaledContents(False)
        self.lblCreateTaskSubtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblCreateTaskSubtitle.setWordWrap(False)
        self.lblCreateTaskSubtitle.setObjectName("lblCreateTaskSubtitle")
        self.horizontalLayout.addWidget(self.frame)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 76, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblTime.setText(_translate("MainWindow", "17 : 04"))
        self.lblDate.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">2025年5月25日 星期日</span></p></body></html>"))
        self.lblCreateTaskTitle.setText(_translate("MainWindow", "我要派件"))
        self.lblCreateTaskSubtitle.setText(_translate("MainWindow", "开始新的配送任务"))
import ui_pkg.scripts.Four_cabin.resources_rc
